[DEFAULT]

path_to_CmdLib = C:\Program Files\New Focus\New Focus Picomotor Application\Samples
# path to the "Samples" folder of the Picomotor application

# Use Serial Number to controllers
SN_mirror_1 = 8743-CL 11497

SN_mirror_2 = 8743-CL 11497

SN_HWP = 8742 14119

axis_mirror_1X = 1
axis_mirror_1Y = 1
axis_mirror_2X = 2
axis_mirror_2Y = 2
axis_HWP_1 = 1
axis_HWP_2 = 2
