[DEFAULT]

path_to_CmdLib = C:\Program Files\New Focus\New Focus Picomotor Application\Samples
# path to the "Samples" folder of the Picomotor application

# Controllers are identified by IP-Address when communicating over Ethernet
#key_mirror_1 = 192.168.48.30
SN_mirror_1 = 8742 36821

#key_mirror_2 = 192.168.48.29
SN_mirror_2 = 8742 13798

#key_HWP = 192.168.48.30
SN_HWP = 8742 36821

axis_mirror_1X = 3
axis_mirror_1Y = 4
axis_mirror_2X = 1
axis_mirror_2Y = 2
axis_HWP_1 = 1
axis_HWP_2 = 2
