[DEFAULT]
# initial values determined 2019-11-25

mirror_distance = 2653
# Distance between mirrors, mm

undulator_distance = 6010
# Distance from mirror 2 to undulator centre, mm

# Mirror motor responses in Microrad per Motor Step
M1Y_pos = 1.49
M1Y_neg = 1.32
M1X_pos = 0.93
M1X_neg = 0.93

M2Y_pos = 1.41
M2Y_neg = 1.39
M2X_pos = 1.02
M2X_neg = 0.99

[saved_values]
# space for new values without deleting the original ones
# please do not delete this section, even when it is empty!
