[DEFAULT]
# initial values determined 2021-04-15

mirror_distance = 2285
# Distance between mirrors, mm

undulator_distance = 6010
# Distance from mirror 2 to undulator centre, mm

# Mirror motor responses in Microrad per Motor Step
M1Y_pos = -2.76
M1Y_neg = -2.76
M1X_pos = 1.89
M1X_neg = 1.89

M2Y_pos = -2.76
M2Y_neg = -2.76
M2X_pos = 1.89
M2X_neg = 1.89
# Werte fuer beide Spiegel zunaechst aus den Messungen fuer Spiegel 2, da
# Messung fuer Spiegel 1 nur durch Linsen moeglich, verhalten der Spiegel
# scheint identisch zu sein.
# Negative Werte bei Y, da Spiegelhalter umgekehrt aufgebaut

# 2025-11-21 neue Messung fuer Spiegel 1 (neue Motoren eingebaut) ergibt genau die gleichen Zahlen.

[saved_values]
# space for new values without deleting the original ones
# please do not delete this section, even when it is empty!
