<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
  <title>Formula smoke test: BPM3/BPM4 upstream X angle only</title>
  <show_legend>true</show_legend>
  <show_toolbar>true</show_toolbar>
  <grid>true</grid>
  <update_period>1.0</update_period>
  <scroll_step>5</scroll_step>
  <scroll>true</scroll>
  <start>-10 minutes</start>
  <end>now</end>
  <archive_rescale>NONE</archive_rescale>
  <foreground>
    <red>0</red>
    <green>0</green>
    <blue>0</blue>
  </foreground><background>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
  </background><title_font>Liberation Sans|16|1</title_font>
  <label_font>Liberation Sans|10|1</label_font>
  <scale_font>Liberation Sans|8|0</scale_font>
  <legend_font>Liberation Sans|9|0</legend_font>
  <axes>
    <axis>
      <visible>true</visible>
      <name>BPM3/BPM4 X raw [mm]</name>
      <use_axis_name>true</use_axis_name>
      <use_trace_names>false</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color><min>-0.3</min>
      <max>0.0</max>
      <grid>true</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis><axis>
      <visible>true</visible>
      <name>Upstream X angle [mrad]</name>
      <use_axis_name>true</use_axis_name>
      <use_trace_names>false</use_trace_names>
      <right>true</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color><min>-0.05</min>
      <max>0.05</max>
      <grid>true</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis><axis>
      <visible>false</visible>
      <name>hidden</name>
      <use_axis_name>true</use_axis_name>
      <use_trace_names>false</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color><min>-1.0</min>
      <max>1.0</max>
      <grid>true</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis>
  </axes><annotations />
  <pvlist>
    <pv>
      <display_name>dep BPMZ3L2RP:rdX</display_name>
      <visible>false</visible>
      <name>BPMZ3L2RP:rdX</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ4L2RP:rdX</display_name>
      <visible>false</visible>
      <name>BPMZ4L2RP:rdX</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ5L2RP:rdX</display_name>
      <visible>false</visible>
      <name>BPMZ5L2RP:rdX</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ6L2RP:rdX</display_name>
      <visible>false</visible>
      <name>BPMZ6L2RP:rdX</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ3L2RP:rdY</display_name>
      <visible>false</visible>
      <name>BPMZ3L2RP:rdY</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ4L2RP:rdY</display_name>
      <visible>false</visible>
      <name>BPMZ4L2RP:rdY</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ5L2RP:rdY</display_name>
      <visible>false</visible>
      <name>BPMZ5L2RP:rdY</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep BPMZ6L2RP:rdY</display_name>
      <visible>false</visible>
      <name>BPMZ6L2RP:rdY</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep HS1P2K3RP:setCur</display_name>
      <visible>false</visible>
      <name>HS1P2K3RP:setCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep HS3P1L4RP:setCur</display_name>
      <visible>false</visible>
      <name>HS3P1L4RP:setCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep HS3P2L4RP:setCur</display_name>
      <visible>false</visible>
      <name>HS3P2L4RP:setCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep HS1P1K1RP:setCur</display_name>
      <visible>false</visible>
      <name>HS1P1K1RP:setCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCOPE1ZULP:h1p1:rdAmplAv</display_name>
      <visible>false</visible>
      <name>SCOPE1ZULP:h1p1:rdAmplAv</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCOPE1ZULP:h1p1:rdAmpl</display_name>
      <visible>false</visible>
      <name>SCOPE1ZULP:h1p1:rdAmpl</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCOPE1ZULP:h1p2:rdAmplAv</display_name>
      <visible>false</visible>
      <name>SCOPE1ZULP:h1p2:rdAmplAv</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCOPE1ZULP:h1p3:rdAmplAv</display_name>
      <visible>false</visible>
      <name>SCOPE1ZULP:h1p3:rdAmplAv</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep QPD01ZL2RP:rdSigmaXav</display_name>
      <visible>false</visible>
      <name>QPD01ZL2RP:rdSigmaXav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep QPD01ZL2RP:rdSigmaYav</display_name>
      <visible>false</visible>
      <name>QPD01ZL2RP:rdSigmaYav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep QPD00ZL4RP:rdSigmaXav</display_name>
      <visible>false</visible>
      <name>QPD00ZL4RP:rdSigmaXav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep QPD00ZL4RP:rdSigmaYav</display_name>
      <visible>false</visible>
      <name>QPD00ZL4RP:rdSigmaYav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep CUM1ZK3RP:rdCur</display_name>
      <visible>false</visible>
      <name>CUM1ZK3RP:rdCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep CUM1ZK3RP:rdLt100</display_name>
      <visible>false</visible>
      <name>CUM1ZK3RP:rdLt100</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep CUM1ZK3RP:rdLt3</display_name>
      <visible>false</visible>
      <name>CUM1ZK3RP:rdLt3</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MCLKHGP:rdFrq499</display_name>
      <visible>false</visible>
      <name>MCLKHGP:rdFrq499</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MCLKHGP:setFrq499</display_name>
      <visible>false</visible>
      <name>MCLKHGP:setFrq499</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep ERMPCGP:rdRmp</display_name>
      <visible>false</visible>
      <name>ERMPCGP:rdRmp</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep PAHRP:NRVD:rdVoltCav</display_name>
      <visible>false</visible>
      <name>PAHRP:NRVD:rdVoltCav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep PAHRP:setVoltCav</display_name>
      <visible>false</visible>
      <name>PAHRP:setVoltCav</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep Q1P1L2RP:setCur</display_name>
      <visible>false</visible>
      <name>Q1P1L2RP:setCur</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep U125IL2RP:BasePmGap.A</display_name>
      <visible>false</visible>
      <name>U125IL2RP:BasePmGap.A</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep PURITYCCP:calculation</display_name>
      <visible>false</visible>
      <name>PURITYCCP:calculation</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep OPCHECKCCP:calcCurrLife</display_name>
      <visible>false</visible>
      <name>OPCHECKCCP:calcCurrLife</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC05VP</display_name>
      <visible>false</visible>
      <name>AKC05VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC06VP</display_name>
      <visible>false</visible>
      <name>AKC06VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC10VP</display_name>
      <visible>false</visible>
      <name>AKC10VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC11VP</display_name>
      <visible>false</visible>
      <name>AKC11VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC12VP</display_name>
      <visible>false</visible>
      <name>AKC12VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep AKC13VP</display_name>
      <visible>false</visible>
      <name>AKC13VP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MNF1C1L2RP</display_name>
      <visible>false</visible>
      <name>MNF1C1L2RP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MNF1C2L2RP</display_name>
      <visible>false</visible>
      <name>MNF1C2L2RP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MNF2C2L2RP</display_name>
      <visible>false</visible>
      <name>MNF2C2L2RP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep MNF2C1L2RP</display_name>
      <visible>false</visible>
      <name>MNF2C1L2RP</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCRYZK3RP.VAL</display_name>
      <visible>false</visible>
      <name>SCRYZK3RP.VAL</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep WFGEN2C1CP:setVolt</display_name>
      <visible>false</visible>
      <name>WFGEN2C1CP:setVolt</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep WFGEN2C1CP:stOut</display_name>
      <visible>false</visible>
      <name>WFGEN2C1CP:stOut</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep SCOPE1ZULP:rdAvLength</display_name>
      <visible>false</visible>
      <name>SCOPE1ZULP:rdAvLength</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep PAHRP:Ctrl:rdCavTempBody</display_name>
      <visible>false</visible>
      <name>PAHRP:Ctrl:rdCavTempBody</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep PAHRP:Ctrl:rdPlngPos</display_name>
      <visible>false</visible>
      <name>PAHRP:Ctrl:rdPlngPos</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep TUNEZRP:measX</display_name>
      <visible>false</visible>
      <name>TUNEZRP:measX</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep TUNEZRP:measY</display_name>
      <visible>false</visible>
      <name>TUNEZRP:measY</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>dep TUNEZRP:measZ</display_name>
      <visible>false</visible>
      <name>TUNEZRP:measZ</name>
      <axis>9</axis>
      <color>
        <red>127</red>
        <green>127</green>
        <blue>127</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>1</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>BPM3 X raw</display_name>
      <visible>true</visible>
      <name>BPMZ3L2RP:rdX</name>
      <axis>0</axis>
      <color>
        <red>31</red>
        <green>119</green>
        <blue>180</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><pv>
      <display_name>BPM4 X raw</display_name>
      <visible>true</visible>
      <name>BPMZ4L2RP:rdX</name>
      <axis>0</axis>
      <color>
        <red>44</red>
        <green>160</green>
        <blue>44</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <request>RAW</request>
    </pv><formula>
      <display_name>BPM34 upstream X angle [mrad]</display_name>
      <visible>true</visible>
      <name>BPM34 upstream X angle [mrad]</name>
      <axis>1</axis>
      <color>
        <red>214</red>
        <green>39</green>
        <blue>40</blue>
      </color><trace_type>AREA</trace_type>
      <linewidth>3</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>259200</ring_size>
      <formula>((x4-x3)/0.8594)</formula>
      <input>
        <pv>BPMZ3L2RP:rdX</pv>
        <name>x3</name>
      </input><input>
        <pv>BPMZ4L2RP:rdX</pv>
        <name>x4</name>
      </input>
    </formula>
  </pvlist>
</databrowser>
